unit NeoClassicIconNames;

{ NeoClassicIcons - classic 16x16 pixel-art icons for Lazarus.
  THIS FILE IS GENERATED by tools/build.py - do not edit by hand.
  SPDX-License-Identifier: MIT }

{$mode objfpc}{$H+}

interface

const
  NeoClassicIconCount = 141;

  { Fingerprint of the icon artwork. It changes whenever a pixel changes, which
    makes FPC recompile the units that link neoclassicicons_images.res -
    otherwise an edited icon would keep showing the old, cached resource. }
  NeoClassicIconSetHash = 'a7d018de45662e2e';

  // Image indexes in TNeoClassicImageList
  // File
  nciDocument        = 0;   { Blank document }
  nciDocumentExport  = 1;   { Export }
  nciDocumentImport  = 2;   { Import }
  nciDocumentNew     = 3;   { New document }
  nciDocumentOpen    = 4;   { Open }
  nciDocumentPreview = 5;   { Print preview }
  nciDocumentPrint   = 6;   { Print }
  nciDocumentSave    = 7;   { Save }
  nciDocumentSaveAll = 8;   { Save all }
  nciDocumentSaveAs  = 9;   { Save as }
  nciDocumentText    = 10;  { Text document }
  nciFolder          = 11;  { Folder }
  nciFolderAdd       = 12;  { New folder }
  nciFolderOpen      = 13;  { Open folder }
  nciFolderDelete    = 78;  { Delete folder }
  // Edit
  nciEdit            = 14;  { Edit }
  nciEditCopy        = 15;  { Copy }
  nciEditCut         = 16;  { Cut }
  nciEditDelete      = 17;  { Delete }
  nciEditFind        = 18;  { Find }
  nciEditPaste       = 19;  { Paste }
  nciEditRedo        = 20;  { Redo }
  nciEditUndo        = 21;  { Undo }
  nciZoomIn          = 22;  { Zoom in }
  nciZoomOut         = 23;  { Zoom out }
  // Action
  nciAdd             = 24;  { Add }
  nciApply           = 25;  { Apply / OK }
  nciCancel          = 26;  { Cancel }
  nciFilter          = 27;  { Filter }
  nciRefresh         = 28;  { Refresh }
  nciRemove          = 29;  { Remove }
  nciSortAscending   = 30;  { Sort ascending }
  nciSortDescending  = 31;  { Sort descending }
  nciTrash           = 32;  { Recycle bin }
  // Navigation
  nciArrowDown       = 33;  { Down }
  nciArrowLeft       = 34;  { Left / Back }
  nciArrowRight      = 35;  { Right / Forward }
  nciArrowUp         = 36;  { Up }
  nciHome            = 37;  { Home }
  nciNavFirst        = 38;  { First record }
  nciNavLast         = 39;  { Last record }
  nciNavNext         = 40;  { Next record }
  nciNavPrior        = 41;  { Prior record }
  // Data
  nciChartBar        = 42;  { Bar chart }
  nciChartPie        = 43;  { Pie chart }
  nciDatabase        = 44;  { Database }
  nciDatabaseAdd     = 45;  { Add database }
  nciReport          = 46;  { Report }
  nciTable           = 47;  { Table }
  nciTableAdd        = 48;  { Add record }
  nciTableDelete     = 49;  { Delete record }
  nciChartLine       = 79;  { Line chart }
  nciDatabaseDelete  = 80;  { Delete database }
  // Application
  nciAttachment      = 50;  { Attachment }
  nciBarcode         = 51;  { Barcode }
  nciBox             = 52;  { Box / Product }
  nciCalculator      = 53;  { Calculator }
  nciCalendar        = 54;  { Calendar }
  nciCart            = 55;  { Shopping cart }
  nciClock           = 56;  { Clock }
  nciError           = 57;  { Error }
  nciExit            = 58;  { Exit }
  nciFlag            = 59;  { Flag }
  nciGlobe           = 60;  { Internet }
  nciHelp            = 61;  { Help }
  nciImage           = 62;  { Image }
  nciInfo            = 63;  { Information / About }
  nciKey             = 64;  { Key }
  nciLightbulb       = 65;  { Tip }
  nciLock            = 66;  { Lock }
  nciMail            = 67;  { E-mail }
  nciMoney           = 68;  { Money }
  nciPhone           = 69;  { Phone }
  nciSettings        = 70;  { Settings }
  nciStar            = 71;  { Star / Favourite }
  nciTag             = 72;  { Tag / Price }
  nciTruck           = 73;  { Shipping }
  nciUser            = 74;  { User }
  nciUserAdd         = 75;  { Add user }
  nciUsers           = 76;  { Users }
  nciWarning         = 77;  { Warning }
  nciBell            = 81;  { Notification }
  nciBookmark        = 82;  { Bookmark }
  nciBug             = 83;  { Bug / Debug }
  nciBuilding        = 84;  { Company }
  nciCar             = 85;  { Vehicle }
  nciChat            = 86;  { Chat / Comment }
  nciCloud           = 87;  { Cloud }
  nciCreditCard      = 88;  { Credit card }
  nciDownload        = 89;  { Download }
  nciEye             = 90;  { View }
  nciGift            = 91;  { Gift }
  nciHeart           = 92;  { Heart / Like }
  nciHourglass       = 93;  { Wait }
  nciLink            = 94;  { Link }
  nciLocation        = 95;  { Location }
  nciMoon            = 96;  { Night / Dark theme }
  nciPlugin          = 97;  { Plugin }
  nciReceipt         = 98;  { Receipt / Invoice }
  nciShield          = 99;  { Security }
  nciSun             = 100; { Day / Light theme }
  nciTerminal        = 101; { Terminal }
  nciTrophy          = 102; { Trophy / Award }
  nciUpload          = 103; { Upload }
  nciUserDelete      = 104; { Delete user }
  nciWallet          = 105; { Wallet }
  nciWrench          = 106; { Tools }
  // Device
  nciBattery         = 107; { Battery }
  nciCamera          = 108; { Camera }
  nciCd              = 109; { CD / DVD }
  nciComputer        = 110; { Computer }
  nciHardDisk        = 111; { Hard disk }
  nciKeyboard        = 112; { Keyboard }
  nciLaptop          = 113; { Laptop }
  nciMobilePhone     = 114; { Mobile phone }
  nciMonitor         = 115; { Monitor }
  nciMouse           = 116; { Mouse }
  nciNetwork         = 117; { Network }
  nciPower           = 118; { Power }
  nciServer          = 119; { Server }
  nciTv              = 120; { Television }
  // Media
  nciHeadphones      = 121; { Headphones }
  nciMicrophone      = 122; { Microphone }
  nciMusic           = 123; { Music }
  nciMute            = 124; { Mute }
  nciPause           = 125; { Pause }
  nciPlay            = 126; { Play }
  nciRecord          = 127; { Record }
  nciStop            = 128; { Stop }
  nciVideo           = 129; { Video }
  nciVolume          = 130; { Volume }
  // Format
  nciAlignCenter     = 131; { Center }
  nciAlignLeft       = 132; { Align left }
  nciAlignRight      = 133; { Align right }
  nciColorPalette    = 134; { Colour palette }
  nciFont            = 135; { Font }
  nciListBullet      = 136; { Bulleted list }
  nciPaintBrush      = 137; { Paint brush }
  nciTextBold        = 138; { Bold }
  nciTextItalic      = 139; { Italic }
  nciTextUnderline   = 140; { Underline }

  // Resource base names (16 px: NAME, 32 px: NAME_200)
  NeoClassicIconList: array[0..NeoClassicIconCount - 1] of string = (
    'document',
    'document_export',
    'document_import',
    'document_new',
    'document_open',
    'document_preview',
    'document_print',
    'document_save',
    'document_save_all',
    'document_save_as',
    'document_text',
    'folder',
    'folder_add',
    'folder_open',
    'edit',
    'edit_copy',
    'edit_cut',
    'edit_delete',
    'edit_find',
    'edit_paste',
    'edit_redo',
    'edit_undo',
    'zoom_in',
    'zoom_out',
    'add',
    'apply',
    'cancel',
    'filter',
    'refresh',
    'remove',
    'sort_ascending',
    'sort_descending',
    'trash',
    'arrow_down',
    'arrow_left',
    'arrow_right',
    'arrow_up',
    'home',
    'nav_first',
    'nav_last',
    'nav_next',
    'nav_prior',
    'chart_bar',
    'chart_pie',
    'database',
    'database_add',
    'report',
    'table',
    'table_add',
    'table_delete',
    'attachment',
    'barcode',
    'box',
    'calculator',
    'calendar',
    'cart',
    'clock',
    'error',
    'exit',
    'flag',
    'globe',
    'help',
    'image',
    'info',
    'key',
    'lightbulb',
    'lock',
    'mail',
    'money',
    'phone',
    'settings',
    'star',
    'tag',
    'truck',
    'user',
    'user_add',
    'users',
    'warning',
    'folder_delete',
    'chart_line',
    'database_delete',
    'bell',
    'bookmark',
    'bug',
    'building',
    'car',
    'chat',
    'cloud',
    'credit_card',
    'download',
    'eye',
    'gift',
    'heart',
    'hourglass',
    'link',
    'location',
    'moon',
    'plugin',
    'receipt',
    'shield',
    'sun',
    'terminal',
    'trophy',
    'upload',
    'user_delete',
    'wallet',
    'wrench',
    'battery',
    'camera',
    'cd',
    'computer',
    'hard_disk',
    'keyboard',
    'laptop',
    'mobile_phone',
    'monitor',
    'mouse',
    'network',
    'power',
    'server',
    'tv',
    'headphones',
    'microphone',
    'music',
    'mute',
    'pause',
    'play',
    'record',
    'stop',
    'video',
    'volume',
    'align_center',
    'align_left',
    'align_right',
    'color_palette',
    'font',
    'list_bullet',
    'paint_brush',
    'text_bold',
    'text_italic',
    'text_underline'
  );

  // Short English descriptions, same order
  NeoClassicIconTitles: array[0..NeoClassicIconCount - 1] of string = (
    'Blank document',
    'Export',
    'Import',
    'New document',
    'Open',
    'Print preview',
    'Print',
    'Save',
    'Save all',
    'Save as',
    'Text document',
    'Folder',
    'New folder',
    'Open folder',
    'Edit',
    'Copy',
    'Cut',
    'Delete',
    'Find',
    'Paste',
    'Redo',
    'Undo',
    'Zoom in',
    'Zoom out',
    'Add',
    'Apply / OK',
    'Cancel',
    'Filter',
    'Refresh',
    'Remove',
    'Sort ascending',
    'Sort descending',
    'Recycle bin',
    'Down',
    'Left / Back',
    'Right / Forward',
    'Up',
    'Home',
    'First record',
    'Last record',
    'Next record',
    'Prior record',
    'Bar chart',
    'Pie chart',
    'Database',
    'Add database',
    'Report',
    'Table',
    'Add record',
    'Delete record',
    'Attachment',
    'Barcode',
    'Box / Product',
    'Calculator',
    'Calendar',
    'Shopping cart',
    'Clock',
    'Error',
    'Exit',
    'Flag',
    'Internet',
    'Help',
    'Image',
    'Information / About',
    'Key',
    'Tip',
    'Lock',
    'E-mail',
    'Money',
    'Phone',
    'Settings',
    'Star / Favourite',
    'Tag / Price',
    'Shipping',
    'User',
    'Add user',
    'Users',
    'Warning',
    'Delete folder',
    'Line chart',
    'Delete database',
    'Notification',
    'Bookmark',
    'Bug / Debug',
    'Company',
    'Vehicle',
    'Chat / Comment',
    'Cloud',
    'Credit card',
    'Download',
    'View',
    'Gift',
    'Heart / Like',
    'Wait',
    'Link',
    'Location',
    'Night / Dark theme',
    'Plugin',
    'Receipt / Invoice',
    'Security',
    'Day / Light theme',
    'Terminal',
    'Trophy / Award',
    'Upload',
    'Delete user',
    'Wallet',
    'Tools',
    'Battery',
    'Camera',
    'CD / DVD',
    'Computer',
    'Hard disk',
    'Keyboard',
    'Laptop',
    'Mobile phone',
    'Monitor',
    'Mouse',
    'Network',
    'Power',
    'Server',
    'Television',
    'Headphones',
    'Microphone',
    'Music',
    'Mute',
    'Pause',
    'Play',
    'Record',
    'Stop',
    'Video',
    'Volume',
    'Center',
    'Align left',
    'Align right',
    'Colour palette',
    'Font',
    'Bulleted list',
    'Paint brush',
    'Bold',
    'Italic',
    'Underline'
  );

{ Returns the image index for an icon name such as 'document_save', or -1. }
function NeoClassicIconIndex(const AName: string): Integer;

implementation

uses
  SysUtils;

function NeoClassicIconIndex(const AName: string): Integer;
begin
  for Result := 0 to NeoClassicIconCount - 1 do
    if SameText(NeoClassicIconList[Result], AName) then
      Exit;
  Result := -1;
end;

end.
