unit NeoClassicIconNames;

{ NeoClassicIcons - classic 16x16 pixel-art icons for Lazarus.
  THIS FILE IS GENERATED by tools/build.py - do not edit by hand.
  SPDX-License-Identifier: MIT }

{$mode objfpc}{$H+}

interface

const
  NeoClassicIconCount = 78;

  // Image indexes in TNeoClassicImageList
  // File
  nciDocument        = 0;   { Blank document }
  nciDocumentExport  = 1;   { Export }
  nciDocumentImport  = 2;   { Import }
  nciDocumentNew     = 3;   { New document }
  nciDocumentOpen    = 4;   { Open }
  nciDocumentPreview = 5;   { Print preview }
  nciDocumentPrint   = 6;   { Print }
  nciDocumentSave    = 7;   { Save }
  nciDocumentSaveAll = 8;   { Save all }
  nciDocumentSaveAs  = 9;   { Save as }
  nciDocumentText    = 10;  { Text document }
  nciFolder          = 11;  { Folder }
  nciFolderAdd       = 12;  { New folder }
  nciFolderOpen      = 13;  { Open folder }
  // Edit
  nciEdit            = 14;  { Edit }
  nciEditCopy        = 15;  { Copy }
  nciEditCut         = 16;  { Cut }
  nciEditDelete      = 17;  { Delete }
  nciEditFind        = 18;  { Find }
  nciEditPaste       = 19;  { Paste }
  nciEditRedo        = 20;  { Redo }
  nciEditUndo        = 21;  { Undo }
  nciZoomIn          = 22;  { Zoom in }
  nciZoomOut         = 23;  { Zoom out }
  // Action
  nciAdd             = 24;  { Add }
  nciApply           = 25;  { Apply / OK }
  nciCancel          = 26;  { Cancel }
  nciFilter          = 27;  { Filter }
  nciRefresh         = 28;  { Refresh }
  nciRemove          = 29;  { Remove }
  nciSortAscending   = 30;  { Sort ascending }
  nciSortDescending  = 31;  { Sort descending }
  nciTrash           = 32;  { Recycle bin }
  // Navigation
  nciArrowDown       = 33;  { Down }
  nciArrowLeft       = 34;  { Left / Back }
  nciArrowRight      = 35;  { Right / Forward }
  nciArrowUp         = 36;  { Up }
  nciHome            = 37;  { Home }
  nciNavFirst        = 38;  { First record }
  nciNavLast         = 39;  { Last record }
  nciNavNext         = 40;  { Next record }
  nciNavPrior        = 41;  { Prior record }
  // Data
  nciChartBar        = 42;  { Bar chart }
  nciChartPie        = 43;  { Pie chart }
  nciDatabase        = 44;  { Database }
  nciDatabaseAdd     = 45;  { Add database }
  nciReport          = 46;  { Report }
  nciTable           = 47;  { Table }
  nciTableAdd        = 48;  { Add record }
  nciTableDelete     = 49;  { Delete record }
  // Application
  nciAttachment      = 50;  { Attachment }
  nciBarcode         = 51;  { Barcode }
  nciBox             = 52;  { Box / Product }
  nciCalculator      = 53;  { Calculator }
  nciCalendar        = 54;  { Calendar }
  nciCart            = 55;  { Shopping cart }
  nciClock           = 56;  { Clock }
  nciError           = 57;  { Error }
  nciExit            = 58;  { Exit }
  nciFlag            = 59;  { Flag }
  nciGlobe           = 60;  { Internet }
  nciHelp            = 61;  { Help }
  nciImage           = 62;  { Image }
  nciInfo            = 63;  { Information / About }
  nciKey             = 64;  { Key }
  nciLightbulb       = 65;  { Tip }
  nciLock            = 66;  { Lock }
  nciMail            = 67;  { E-mail }
  nciMoney           = 68;  { Money }
  nciPhone           = 69;  { Phone }
  nciSettings        = 70;  { Settings }
  nciStar            = 71;  { Star / Favourite }
  nciTag             = 72;  { Tag / Price }
  nciTruck           = 73;  { Shipping }
  nciUser            = 74;  { User }
  nciUserAdd         = 75;  { Add user }
  nciUsers           = 76;  { Users }
  nciWarning         = 77;  { Warning }

  // Resource base names (16 px: NAME, 32 px: NAME_200)
  NeoClassicIconList: array[0..NeoClassicIconCount - 1] of string = (
    'document',
    'document_export',
    'document_import',
    'document_new',
    'document_open',
    'document_preview',
    'document_print',
    'document_save',
    'document_save_all',
    'document_save_as',
    'document_text',
    'folder',
    'folder_add',
    'folder_open',
    'edit',
    'edit_copy',
    'edit_cut',
    'edit_delete',
    'edit_find',
    'edit_paste',
    'edit_redo',
    'edit_undo',
    'zoom_in',
    'zoom_out',
    'add',
    'apply',
    'cancel',
    'filter',
    'refresh',
    'remove',
    'sort_ascending',
    'sort_descending',
    'trash',
    'arrow_down',
    'arrow_left',
    'arrow_right',
    'arrow_up',
    'home',
    'nav_first',
    'nav_last',
    'nav_next',
    'nav_prior',
    'chart_bar',
    'chart_pie',
    'database',
    'database_add',
    'report',
    'table',
    'table_add',
    'table_delete',
    'attachment',
    'barcode',
    'box',
    'calculator',
    'calendar',
    'cart',
    'clock',
    'error',
    'exit',
    'flag',
    'globe',
    'help',
    'image',
    'info',
    'key',
    'lightbulb',
    'lock',
    'mail',
    'money',
    'phone',
    'settings',
    'star',
    'tag',
    'truck',
    'user',
    'user_add',
    'users',
    'warning'
  );

  // Short English descriptions, same order
  NeoClassicIconTitles: array[0..NeoClassicIconCount - 1] of string = (
    'Blank document',
    'Export',
    'Import',
    'New document',
    'Open',
    'Print preview',
    'Print',
    'Save',
    'Save all',
    'Save as',
    'Text document',
    'Folder',
    'New folder',
    'Open folder',
    'Edit',
    'Copy',
    'Cut',
    'Delete',
    'Find',
    'Paste',
    'Redo',
    'Undo',
    'Zoom in',
    'Zoom out',
    'Add',
    'Apply / OK',
    'Cancel',
    'Filter',
    'Refresh',
    'Remove',
    'Sort ascending',
    'Sort descending',
    'Recycle bin',
    'Down',
    'Left / Back',
    'Right / Forward',
    'Up',
    'Home',
    'First record',
    'Last record',
    'Next record',
    'Prior record',
    'Bar chart',
    'Pie chart',
    'Database',
    'Add database',
    'Report',
    'Table',
    'Add record',
    'Delete record',
    'Attachment',
    'Barcode',
    'Box / Product',
    'Calculator',
    'Calendar',
    'Shopping cart',
    'Clock',
    'Error',
    'Exit',
    'Flag',
    'Internet',
    'Help',
    'Image',
    'Information / About',
    'Key',
    'Tip',
    'Lock',
    'E-mail',
    'Money',
    'Phone',
    'Settings',
    'Star / Favourite',
    'Tag / Price',
    'Shipping',
    'User',
    'Add user',
    'Users',
    'Warning'
  );

{ Returns the image index for an icon name such as 'document_save', or -1. }
function NeoClassicIconIndex(const AName: string): Integer;

implementation

uses
  SysUtils;

function NeoClassicIconIndex(const AName: string): Integer;
begin
  for Result := 0 to NeoClassicIconCount - 1 do
    if SameText(NeoClassicIconList[Result], AName) then
      Exit;
  Result := -1;
end;

end.
